<?php
/**
 * Fired when the plugin is uninstalled (deleted via the Plugins screen).
 *
 * This file intentionally does NOT delete any media files (originals or
 * generated WebP images). Only the plugin's own settings option is removed,
 * and only after this file's presence is confirmed by WordPress core.
 *
 * @package PNG_To_WebP_Converter
 */
 

// If uninstall is not called from WordPress, exit.
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

/*
 * Remove the plugin's settings option only.
 *
 * Media files -- both original images and any WebP versions generated by
 * this plugin -- are intentionally left untouched. They remain fully
 * functional Media Library attachments after uninstall. This avoids any
 * silent, destructive cleanup of user content.
 */
delete_option( 'ptw_settings' );

/*
 * Post meta added by this plugin (which links original attachments to their
 * WebP counterparts) is left in place, since it is harmless metadata attached
 * to the user's own media and removing it provides no benefit while adding
 * uninstall complexity and risk.
 */
